Update akash commands
vitwit/faucet pull request #10
Opened 2020-06-04 11:37 UTC by akhilkumarpilli

2020-06-05 17:12 UTC, anilcse requested changes
Looks good, just a few changes

2020-06-05 17:12 UTC, anilCSE commented on backend/faucet.go
> +	}
```suggestion
	if len(queryRes.Value.Coins) == 0 {
		return nil
	}
	
	balance, err := strconv.ParseFloat(queryRes.Value.Coins[0].Amount, 64)
	if err != nil {
		return nil
	}
```

2020-06-05 17:12 UTC, anilCSE commented on backend/faucet.go
> +	if balance < float64(10)*math.Pow(10, 6) || accErr != nil {
Use MAX_TOKENS_ALLOWED config variable. 
```suggestion
	if balance < MAX_TOKENS_ALLOWED || accErr != nil {
```

2020-06-05 17:12 UTC, anilCSE commented on backend/faucet.go
> +	if len(address) != 44 {
Use a config/constant or use regex

2020-06-06 13:46 UTC, anilcse approved these changes
lgtm, can you just change float64 to int64 for balances?

2020-06-06 13:53 UTC, akhilkumarpilli commented
I think float64 is fine. Balance will be in decimals when we withdraw rewards.

2020-06-06 14:12 UTC, anilCSE commented
No, chain doesn't support decimals. It's just the display on the client side that will display decimals. Cosmos balances are all i64

2020-06-06 14:14 UTC, akhilkumarpilli commented
But we are executing client commands for checking balance. Will it be fine if we change to i64?

2020-06-06 15:12 UTC, anilCSE commented
Understand, no problem. Let's keep it f64

2020-06-06 15:12 UTC, merged